services:
  devcontainer:
    build:
      context: ..
      dockerfile: Dockerfile
      target: dev
    env_file:
      - path: ../.env.example
        required: true
      - path: ../.env
        required: false
    environment:
      DOCKER_INIT_USERNAME: vscode
    volumes:
      - ..:/workspaces/latex-infrastructure:cached
      - /var/run/docker.sock:/var/run/docker-host.sock
    entrypoint: ['/usr/local/share/docker-init.sh']
    command: ['sleep', 'infinity']
    init: true
